res:
    customer:
        dataSource:
            server: ${CUSTOMER_DATABASE_HOST}:${CUSTOMER_DATABASE_PORT}
        etcd:
            server: ${CUSTOMER_ETCD_HOST}:${CUSTOMER_ETCD_PORT}
        integration:
            gateway:
                port: ${CUSTOMER_GATEWAY_PORT}
        metadata:
            service:
                url: ${CUSTOMER_GATEWAY_HOST}:${res.customer.integration.gateway.port}

eureka:
    client:
        enabled: ${CUSTOMER_EUREKA_CLIENT_ENABLED}
        serviceUrl:
            defaultZone: http://${CUSTOMER_EUREKA_HOST}:${CUSTOMER_EUREKA_PORT}/eureka

feign:
    circuitbreaker:
        enabled: ${CUSTOMER_CIRCUIT_BREAKER_ENABLED}
    client:
        config:
            country-state-city-api-service:
                loggerLevel: ${CUSTOMER_FEIGN_LOGGING_LEVEL}
            default:
                loggerLevel: ${CUSTOMER_FEIGN_LOGGING_LEVEL}
            metadata-service:
                loggerLevel: ${CUSTOMER_FEIGN_LOGGING_LEVEL}

logging:
    level:
        org.hibernate.SQL: ${CUSTOMER_LOGGING_LEVEL}
        org.hibernate.type.descriptor.sql.BasicBinder: ${CUSTOMER_LOGGING_LEVEL}

server:
    port: ${CUSTOMER_SERVER_PORT}

spring:
    zipkin:
        baseUrl: http://${CUSTOMER_ZIPKIN_HOST}:${CUSTOMER_ZIPKIN_PORT}
        enabled: ${CUSTOMER_ZIPKIN_CLIENT_ENABLED}

springdoc:
    swagger-ui:
        enabled: ${CUSTOMER_SWAGGER_ENABLED}
