#mode:
#  type: Standalone
#  repository:
#    type: JDBC
#    props:
#      path: res_customer_db

mode:
  type: Cluster
  repository:
    type: etcd
    props:
      namespace: customer
      server-lists: http://localhost:2379


dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/res_customer_db_ds_0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: Razor1911.
    maxPoolSize: 10
  ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/res_customer_db_ds_1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: Razor1911.
    maxPoolSize: 10
  ds_2:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/res_customer_db_ds_2?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: Razor1911.
    maxPoolSize: 10

rules:
  - !SHARDING
    #tables:
    #  account:
    #    actualDataNodes: res_customer_db_ds_$->{0..2}.account
    #    tableStrategy:
    #      none:
    #      standard:
    #        shardingColumn: id
    #        shardingAlgorithmName: account_inline
    #    keyGenerateStrategy:
    #      column: id
    #      keyGeneratorName: snowflake_generator
    #bindingTables:
    #  - account
    #broadcastTables:
    #  - address
    defaultDatabaseStrategy:
      standard:
        shardingColumn: email_id
        shardingAlgorithmName: database_inline

    shardingAlgorithms:
      database_inline:
        type: INLINE
        props:
          algorithm-expression: res_customer_db_ds_${email_id % 2}

      #account_inline:
      #  type: INLINE
      #  props:
      #    algorithm-expression: account_$->{id % 2}
    keyGenerators:
      snowflake_generator:
        type: SNOWFLAKE

props:
  sql-show: true
