eureka:
    client:
        enabled: ${ESTABLISHMENT_AREA_EUREKA_CLIENT_ENABLED}
        serviceUrl:
            defaultZone: http://${ESTABLISHMENT_AREA_EUREKA_HOST}:${ESTABLISHMENT_AREA_EUREKA_PORT}/eureka

logging:
    level:
        org:
            hibernate:
                SQL: ${ESTABLISHMENT_AREA_LOGGING_LEVEL}
                type:
                    descriptor:
                        sql:
                            BasicBinder: ${ESTABLISHMENT_AREA_LOGGING_LEVEL}
server:
    port: ${ESTABLISHMENT_AREA_SERVER_PORT}

spring:
    datasource:
        url: jdbc:mysql://${ESTABLISHMENT_AREA_DATABASE_HOST}:${ESTABLISHMENT_AREA_DATABASE_PORT}/res_establishment_area_db?allowPublicKeyRetrieval=true&useSSL=false
    zipkin:
        baseUrl: http://${ESTABLISHMENT_AREA_ZIPKIN_HOST}:${ESTABLISHMENT_AREA_ZIPKIN_PORT}
        enabled: ${ESTABLISHMENT_AREA_ZIPKIN_CLIENT_ENABLED}

springdoc:
    swagger-ui:
        enabled: ${ESTABLISHMENT_AREA_SWAGGER_ENABLED}
