java -jar ^
-DCONFIGURATION_SERVER_PORT=8888 ^
-DCONFIGURATION_LOGSTASH_ENABLED=false ^
-DLOGBACK_LOGGING_LEVEL=INFO ^
-DCONFIGURATION_LOGSTASH_HOST=localhost ^
-DCONFIGURATION_LOGSTASH_PORT=4560 ^
-DCONFIGURATION_EUREKA_CLIENT_ENABLED=true ^
-DCONFIGURATION_EUREKA_HOST=localhost ^
-DCONFIGURATION_EUREKA_PORT=8761 ^
target\configuration-app.jar