java -jar ^
-DCONFIGURATION_SERVER_PORT=8888 ^
-DCONFIGURATION_LOGSTASH_ENABLED=false ^
-DLOGBACK_LOGGING_LEVEL=info ^
-DCONFIGURATION_LOGSTASH_HOST=localhost ^
-DCONFIGURATION_LOGSTASH_PORT=4560 ^
target\configuration-app.jar