eureka:
    client:
        enabled: ${MENU_EUREKA_CLIENT_ENABLED}
        serviceUrl:
            defaultZone: http://${MENU_EUREKA_HOST}:${MENU_EUREKA_PORT}/eureka

logging:
    level:
        org:
            hibernate:
                SQL: ${MENU_LOGGING_LEVEL}
                type:
                    descriptor:
                        sql:
                            BasicBinder: ${MENU_LOGGING_LEVEL}

server:
    port: ${MENU_SERVER_PORT}

spring:
    datasource:
        url: jdbc:mysql://${MENU_DATABASE_HOST}:${MENU_DATABASE_PORT}/res_menu_db
    zipkin:
        baseUrl: http://${MENU_ZIPKIN_HOST}:${MENU_ZIPKIN_PORT}
        enabled: ${MENU_ZIPKIN_CLIENT_ENABLED}

springdoc:
    swagger-ui:
        enabled: ${MENU_SWAGGER_ENABLED}
